spring:
  profiles:
    active: dev



management:

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  secret: secret
  expiration: 86400000